ooiuistatusdb:
  image: oceanzus/docker_postgis
  volumes:
   - $HOME/statusdb_data:/var/lib/postgresql
  environment:
    USERNAME: ooiui
    PASS: ooiui

web:
  build: .
  command: python status_handler.py
  environment:
    DB_PORT: 5432
    DB_USER: ooiui
    DB_PASS: ooiui
    DB_HOST: ooiuistatusdb
    DB_NAME: postgres
    DB_RESET: true
  expose:
   - "4070"
  ports:
   - "10.171.76.246:4070:4070"
  volumes:
   - .:/code
  links:
   - ooiuistatusdb
