status_handler:
    service_mode:       'demo'         # switch: values 'live' or 'demo'
    wsgi_server:
        url:            127.0.0.1      # wsgi service host url
        port:           4070           # wsgi service port
        routes_url:     localhost      # ooiui services host url
        routes_port:    4000           # ooiui services port
        routes_command: /list_routes   # ooiui route to fetch app.url_map for routes and endpoints (eg. /list_routes)
        routes_timeout_connect: 5      # connect timeout (should be greater than 3 secs)
        routes_timeout_read: 45        # read timeout (adjust to accommodate latency)
    postgresql_server:
        host:     localhost
        port:     5432
        username: ednadonoughe
        password:
        database: pstats
    uframe_server:
        url:      '/localhost/dummy/'
        port:     2020
        username: uframe
        password: password
